[package]
authors = ["Matthew Waters <matthew@centricular.com>"]
build = "build.rs"
description = "FFI bindings to libgstvulkan-1.0 (Wayland support)"
documentation = "https://gstreamer.pages.freedesktop.org/gstreamer-rs/stable/latest/docs/gstreamer_vulkan_wayland_sys/"
keywords = ["ffi", "gstreamer", "gnome", "multimedia"]
license = "MIT"
name = "gstreamer-vulkan-wayland-sys"
readme = "README.md"

[package.version]
workspace = true

[package.categories]
workspace = true

[package.repository]
workspace = true

[package.homepage]
workspace = true

[package.edition]
workspace = true

[package.rust-version]
workspace = true

[package.metadata.system-deps.gstreamer_vulkan_wayland_1_0]
name = "gstreamer-vulkan-wayland-1.0"
version = "1.20"

[package.metadata.system-deps.gstreamer_vulkan_wayland_1_0.v1_22]
version = "1.22"

[package.metadata.system-deps.gstreamer_vulkan_wayland_1_0.v1_24]
version = "1.24"

[package.metadata.system-deps.gstreamer_vulkan_wayland_1_0.v1_26]
version = "1.26"

[package.metadata.system-deps.gstreamer_vulkan_wayland_1_0.v1_28]
version = "1.27"

[package.metadata.system-deps.gstreamer_vulkan_wayland_1_0.v1_20]
version = "1.20"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--generate-link-to-definition"]

[lib]
name = "gstreamer_vulkan_wayland_sys"

[dependencies]
libc = "0.2"

[dependencies.glib-sys]
workspace = true

[dependencies.gstreamer-vulkan-sys]
workspace = true

[build-dependencies]
system-deps = "7"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
v1_20 = []
v1_22 = ["v1_20"]
v1_24 = ["v1_22"]
v1_26 = ["v1_24"]
v1_28 = ["v1_26"]
