[package]
name = "gstreamer-vulkan"
authors = ["Matthew Waters <matthew@centricular.com>"]
description = "Rust bindings for GStreamer Vulkan library"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://gstreamer.pages.freedesktop.org/gstreamer-rs/stable/latest/docs/gstreamer_vulkan/"
keywords = ["gstreamer", "multimedia", "audio", "video", "gnome"]
version.workspace = true
categories.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
libc = "0.2"
gstreamer-vulkan-sys.workspace = true
glib.workspace = true
gst.workspace = true
gst-base.workspace = true
gst-video.workspace = true
serde = { version = "1.0", optional = true }
once_cell = "1"

[dev-dependencies]
gir-format-check = "0.1"
serde_json = "1.0"

[features]
default = []
v1_20 = ["gst/v1_20", "gst-base/v1_20", "gst-video/v1_20", "gstreamer-vulkan-sys/v1_20"]
v1_22 = ["gst/v1_22", "gst-base/v1_22", "gst-video/v1_22", "gstreamer-vulkan-sys/v1_22", "v1_20"]
v1_24 = ["gst/v1_24", "gst-base/v1_24", "gst-video/v1_24", "gstreamer-vulkan-sys/v1_24", "v1_22"]
v1_26 = ["gst/v1_26", "gst-base/v1_26", "gst-video/v1_26", "gstreamer-vulkan-sys/v1_26", "v1_24"]
v1_26_4 = ["gst/v1_26", "gst-base/v1_26", "gst-video/v1_26", "gstreamer-vulkan-sys/v1_26_4", "v1_26"]
v1_28 = ["gst/v1_28", "gst-base/v1_28", "gst-video/v1_28", "gstreamer-vulkan-sys/v1_28", "v1_26_4"]
v1_30 = ["gst/v1_30", "gst-base/v1_30", "gst-video/v1_30", "gstreamer-vulkan-sys/v1_30", "v1_28"]
serde = ["dep:serde", "gst/serde", "gst-video/serde"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--generate-link-to-definition"]
