dist: trusty
sudo: required
language: rust
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - libglib2.0-dev
      - libxml2-dev
      - libgtk-3-dev
      - libegl1-mesa
      - libgles2-mesa
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libwayland-egl1-mesa

matrix:
  allow_failures:
    - rust: nightly

script:
    - rustc --version
    - cargo build --all
    - G_DEBUG=fatal_warnings cargo test --all
    - cargo build --all --all-features
    - G_DEBUG=fatal_warnings cargo test --all --all-features

before_install:
- curl -L https://people.freedesktop.org/~slomo/gstreamer-1.14.3.tar.gz | tar xz
- sed -i "s;prefix=/root/gstreamer;prefix=$PWD/gstreamer;g" $PWD/gstreamer/lib/x86_64-linux-gnu/pkgconfig/*.pc
- export PKG_CONFIG_PATH=$PWD/gstreamer/lib/x86_64-linux-gnu/pkgconfig
- export GST_PLUGIN_SYSTEM_PATH=$PWD/gstreamer/lib/x86_64-linux-gnu/gstreamer-1.0
- export GST_PLUGIN_SCANNER=$PWD/gstreamer/libexec/gstreamer-1.0/gst-plugin-scanner
- export PATH=$PATH:$PWD/gstreamer/bin
- export LD_LIBRARY_PATH=$PWD/gstreamer/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
