[workspace]

members = [
  "gstreamer-sys",
  "gstreamer-base-sys",
  "gstreamer-tag-sys",
  "gstreamer-audio-sys",
  "gstreamer-video-sys",
  "gstreamer-pbutils-sys",
  "gstreamer-app-sys",
  "gstreamer-player-sys",
]
