[options]
girs_dir = "gir-files"
library = "GstRtspServer"
version = "1.0"
min_cfg_version = "1.8"
target_path = "gstreamer-rtsp-server-sys"
work_mode = "sys"

extra_versions = [
    "1.18",
    "1.16",
    "1.14",
    "1.12",
    "1.10",
    "1.8",
    "1.6",
    "1.4",
    "1.2",
]

external_libraries = [
    "GLib",
    "GObject",
    "Gio"
]

[[lib_version_overrides]]
version = "1.18"
lib_version = "1.17.2"

[external_libraries]
gstreamer="Gst"
gstreamer_net="GstNet"
gstreamer_sdp="GstSdp"
gstreamer_rtsp="GstRtsp"
