[options]
girs_dir = "gir-files"
library = "GstAudio"
version = "1.0"
min_cfg_version = "1.8"
target_path = "gstreamer-audio"
work_mode = "normal"
concurrency = "send+sync"
generate_safety_asserts = true
single_version_file = true

external_libraries = [
    "GLib",
    "GObject",
    "Gst",
]

generate = [
    "GstAudio.AudioFlags",
    "GstAudio.AudioFormatFlags",
    "GstAudio.AudioLayout",
    "GstAudio.AudioPackFlags",
    "GstAudio.AudioChannelPosition",
    "GstAudio.StreamVolume",
    "GstAudio.StreamVolumeFormat",
]

manual = [
    "GObject.Object",
    "Gst.Object",
    "GstAudio.AudioInfo",
    "GstAudio.AudioFormatInfo",
]

[[object]]
name = "Gst.Caps"
status = "manual"
ref_mode = "ref"

[[object]]
name = "Gst.ClockTime"
status = "manual"
conversion_type = "scalar"

[[object]]
name = "GstAudio.AudioFormat"
status = "generate"

    [[object.member]]
    name = "s16"
    # Platform dependant
    ignore = true

    [[object.member]]
    name = "u16"
    # Platform dependant
    ignore = true

    [[object.member]]
    name = "s24_32"
    # Platform dependant
    ignore = true

    [[object.member]]
    name = "u24_32"
    # Platform dependant
    ignore = true

    [[object.member]]
    name = "s32"
    # Platform dependant
    ignore = true

    [[object.member]]
    name = "u32"
    # Platform dependant
    ignore = true

    [[object.member]]
    name = "s24"
    # Platform dependant
    ignore = true

    [[object.member]]
    name = "u24"
    # Platform dependant
    ignore = true

    [[object.member]]
    name = "s20"
    # Platform dependant
    ignore = true

    [[object.member]]
    name = "u20"
    # Platform dependant
    ignore = true

    [[object.member]]
    name = "s18"
    # Platform dependant
    ignore = true

    [[object.member]]
    name = "u18"
    # Platform dependant
    ignore = true

    [[object.member]]
    name = "f32"
    # Platform dependant
    ignore = true

    [[object.member]]
    name = "f64"
    # Platform dependant
    ignore = true

[[object]]
name = "GstAudio.AudioStreamAlign"
status = "generate"

    [[object.function]]
    name = "process"
    # bool does not signal error
    ignore = true
