[options]
girs_dir = "gir-files"
library = "GstRtsp"
version = "1.0"
min_cfg_version = "1.8"
target_path = "gstreamer-rtsp-sys"
work_mode = "sys"

extra_versions = [
    "1.18",
    "1.16",
    "1.14",
    "1.12",
    "1.10",
    "1.8",
    "1.6",
    "1.4",
    "1.2",
]

external_libraries = [
    "GLib",
    "GObject",
    "Gio"
]

[[lib_version_overrides]]
version = "1.18"
lib_version = "1.17"

[external_libraries]
gstreamer="Gst"
gstreamer_sdp="GstSdp"

[[object]]
name = "GstRtsp.RTSPAuthCredential"
status = "generate"
version = "1.12"

[[object]]
name = "GstRtsp.RTSPAuthParam"
status = "generate"
version = "1.12"

[[object]]
name = "GstRtsp.RTSPMessage"
status = "generate"
    [[object.function]]
    name = "get_type"
    version = "1.14"
