[options]
girs_dir = "gir-files"
library = "GstAudio"
version = "1.0"
min_cfg_version = "1.0"
target_path = "gstreamer-audio-sys"
work_mode = "sys"

external_libraries = [
    "GLib",
    "GObject",
    "Gst",
    "GstBase",
    "GstTag",
]
