[options]
girs_dir = "gir-files"
library = "GstApp"
version = "1.0"
min_cfg_version = "1.8"
target_path = "gstreamer-app"
work_mode = "normal"
concurrency = "send+sync"
generate_safety_asserts = true

external_libraries = [
    "GLib",
    "GObject",
    "Gst",
]

generate = [
    "GstApp.AppStreamType",
]

manual = [
    "GObject.Object",
    "Gst.Object",
    "Gst.Element",
    "Gst.ClockTime",
    "Gst.FlowReturn",
    "Gst.Format",
]

[[object]]
name = "GstApp.AppSink"
status = "generate"
trait = false

[[object]]
name = "GstApp.AppSrc"
status = "generate"
trait = false

    [[object.function]]
    name = "push_buffer"
    # Pass by value
    ignore = true

    [[object.signal]]
    name = "end-of-stream"
    # Action signal
    ignore = true

    [[object.signal]]
    name = "push-buffer"
    # Action signal
    ignore = true

    [[object.signal]]
    name = "push-sample"
    # Action signal
    ignore = true

    [[object.property]]
    name = "current-level-bytes"
    # Has getter function
    ignore = true

    [[object.property]]
    name = "duration"
    # Has getter function
    ignore = true

    [[object.property]]
    name = "max-latency"
    # Has getter function
    ignore = true

    [[object.property]]
    name = "min-latency"
    # Has getter function
    ignore = true

    [[object.property]]
    name = "stream-type"
    # Has getter function
    ignore = true


[[object]]
name = "Gst.Caps"
status = "manual"
ref_mode = "ref"

[[object]]
name = "Gst.Buffer"
status = "manual"
ref_mode = "ref"

[[object]]
name = "Gst.Sample"
status = "manual"
ref_mode = "ref"
