[options]
girs_dir = "gir-files"
library = "GstNet"
version = "1.0"
min_cfg_version = "1.0"
target_path = "gstreamer-net-sys"
work_mode = "sys"

extra_versions = [
    "1.18",
    "1.16",
    "1.14",
    "1.12",
    "1.10",
    "1.8",
    "1.6",
    "1.4",
    "1.2",
]

external_libraries = [
    "GLib",
    "GObject",
    "Gio",
]

[[lib_version_overrides]]
version = "1.18"
lib_version = "1.17"

[external_libraries]
gstreamer="Gst"
