[options]
girs_dir = "gir-files"
library = "GstBase"
version = "1.0"
min_cfg_version = "1.8"
target_path = "gstreamer-base"
work_mode = "normal"
concurrency = "send+sync"
generate_safety_asserts = true
single_version_file = true

external_libraries = [
    "GLib",
    "GObject",
    "Gst",
]

generate = [
    "GstBase.PushSrc",
]

manual = [
    "GObject.Object",
    "GLib.Bytes",
    "Gst.Object",
    "Gst.Element",
    "Gst.BufferPool",
    "Gst.ClockTimeDiff",
    "Gst.ClockReturn",
    "Gst.FlowReturn",
    "Gst.Format",
    "Gst.Pad",
    "Gst.TypeFindProbability",
]

[[object]]
name = "GstBase.Adapter"
status = "generate"
trait = false
concurrency = "send-unique"

    [[object.function]]
    name = "map"
    # Unsafe
    ignore = true

    [[object.function]]
    name = "unmap"
    # Unsafe
    ignore = true

    [[object.function]]
    name = "copy"
    # Unsafe
    ignore = true

    [[object.function]]
    name = "push"
    # Move Buffer
    ignore = true

    [[object.function]]
    name = "take"
    # Useless copying of data
    ignore = true

[[object]]
name = "GstBase.FlowCombiner"
# Manual because ref/unref functions were added much later
status = "manual"
trait = false
concurrency = "none"

[[object]]
name = "GstBase.BaseSink"
subclassing = true
status = "generate"

[[object]]
name = "GstBase.BaseSrc"
subclassing = true
status = "generate"

    [[object.function]]
    name = "submit_buffer_list"
    # Pass by value, to be added manually
    ignore = true

[[object]]
name = "GstBase.BaseTransform"
subclassing = true
status = "generate"

[[object]]
name = "GstBase.Aggregator"
status = "generate"
version = "1.14"

    [[object.function]]
    name = "finish_buffer"
    # Takes ownership
    ignore = true

    [[object.property]]
    name = "latency"
    version = "1.14"

[[object]]
name = "GstBase.AggregatorPad"
status = "generate"
version = "1.14"

[[object]]
name = "GstBase.*"
status = "generate"
    # We'll opt-in for constants at a later time
    [[object.constant]]
    pattern = ".+"
    ignore = true

    [[object.function]]
    name = "type_find_helper_for_data"
    # broken data type
    ignore = true

[[object]]
name = "Gst.Structure"
status = "manual"
ref_mode = "ref-mut"

[[object]]
name = "Gst.Caps"
status = "manual"
ref_mode = "ref"

[[object]]
name = "Gst.Buffer"
status = "manual"
ref_mode = "ref"

[[object]]
name = "Gst.BufferList"
status = "manual"
ref_mode = "ref"

[[object]]
name = "Gst.Sample"
status = "manual"
ref_mode = "ref"

[[object]]
name = "Gst.ClockTime"
status = "manual"
conversion_type = "scalar"
