[options]
girs_dir = "gir-files"
library = "GstPbutils"
version = "1.0"
min_cfg_version = "1.8"
target_path = "gstreamer-pbutils-sys"
work_mode = "sys"

extra_versions = [
    "1.18",
    "1.16",
    "1.14",
    "1.12",
    "1.10",
    "1.8",
    "1.6",
    "1.4",
    "1.2",
]

ignore = [
    "GstPbutils.PLUGINS_BASE_VERSION_MAJOR",
    "GstPbutils.PLUGINS_BASE_VERSION_MINOR",
    "GstPbutils.PLUGINS_BASE_VERSION_MICRO",
    "GstPbutils.PLUGINS_BASE_VERSION_NANO"
]

external_libraries = [
    "GLib",
    "GObject",
]

[[lib_version_overrides]]
version = "1.18"
lib_version = "1.17.2.1"

[external_libraries]
gstreamer="Gst"
gstreamer_audio="GstAudio"
gstreamer_video="GstVideo"
