[options]
girs_dir = "gir-files"
library = "GstGL"
version = "1.0"
min_cfg_version = "1.14"
target_path = "gstreamer-gl-sys"
work_mode = "sys"

extra_versions = [
    "1.18",
    "1.16",
]

ignore = [
    "GstGL.GL_DISPLAY_EGL_NAME",
    "GstGL.GL_COLOR_CONVERT_VIDEO_CAPS",
    "GstGL.GL_COLOR_CONVERT_FORMATS",
    "GstGL.GL_MEMORY_VIDEO_FORMATS_STR",
]

external_libraries = [
    "GLib",
    "GObject",
]

[[lib_version_overrides]]
version = "1.18"
lib_version = "1.17.2"

[external_libraries]
gstreamer="Gst"
gstreamer-base="GstBase"
gstreamer-video="GstVideo"

[[object]]
name = "GstGL.GLDisplayEGL"
status = "generate"
cfg_condition = "feature = \"egl\""
    [[object.function]]
    pattern = ".*"
    cfg_condition = "feature = \"egl\""

[[object]]
name = "GstGL.GLDisplayEGLClass"
status = "generate"
cfg_condition = "feature = \"egl\""

#[[object]]
#name = "GstGL.GL_DISPLAY_EGL_NAME"
#status = "manual"
#cfg_condition = "feature = \"egl\""
#    [[object.constant]]
#    pattern = ".*"
#    cfg_condition = "feature = \"egl\""

#[[object]]
#name = "GstGL.GL_COLOR_CONVERT_VIDEO_CAPS"
#status = "manual"

[[object]]
name = "GstGL.GLDisplayX11"
status = "generate"
cfg_condition = "feature = \"x11\""
    [[object.function]]
    pattern = ".*"
    cfg_condition = "feature = \"x11\""

[[object]]
name = "GstGL.GLDisplayX11Class"
status = "generate"
cfg_condition = "feature = \"x11\""

[[object]]
name = "GstGL.GLDisplayWayland"
status = "generate"
cfg_condition = "feature = \"wayland\""
    [[object.function]]
    pattern = ".*"
    cfg_condition = "feature = \"wayland\""

[[object]]
name = "GstGL.GLDisplayWaylandClass"
status = "generate"
cfg_condition = "feature = \"wayland\""
