[package]
name = "gstreamer"
version = "0.16.4"
authors = ["Sebastian Dr√∂ge <sebastian@centricular.com>"]
categories = ["api-bindings", "multimedia"]
description = "Rust bindings for GStreamer"
repository = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs"
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://gstreamer.freedesktop.org"
documentation = "https://gstreamer.pages.freedesktop.org/gstreamer-rs/gstreamer/"
keywords = ["gstreamer", "multimedia", "audio", "video", "gnome"]
build = "build.rs"

[dependencies]
bitflags = "1.0"
cfg-if = "1.0"
libc = "0.2"
glib-sys = "0.10"
gobject-sys = "0.10"
gstreamer-sys = { version = "0.9", git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs-sys.git", rev = "0.9", features = ["v1_8"] }
glib = "0.10"
num-rational = { version = "0.3", default-features = false, features = [] }
once_cell = "1.0"
futures-core = "0.3"
futures-util = "0.3"
futures-channel = "0.3"
muldiv = "0.2"
serde = { version = "1.0", optional = true }
serde_bytes = { version = "0.11", optional = true }
serde_derive = { version = "1.0", optional = true }
paste = "1.0"
pretty-hex = "0.2"
thiserror = "1"

[build-dependencies]
gstreamer-rs-lgpl-docs = { version = "0.16", path = "../docs", optional = true }

[dev-dependencies]
ron = "0.6"
serde_json = "1.0"
futures-executor = "0.3.1"

[features]
default = []
v1_10 = ["gstreamer-sys/v1_10"]
v1_12 = ["gstreamer-sys/v1_12", "v1_10"]
v1_14 = ["gstreamer-sys/v1_14", "v1_12"]
v1_16 = ["gstreamer-sys/v1_16", "v1_14"]
v1_18 = ["gstreamer-sys/v1_18", "v1_16"]
embed-lgpl-docs = ["gstreamer-rs-lgpl-docs"]
purge-lgpl-docs = ["gstreamer-rs-lgpl-docs"]
dox = ["v1_18", "gstreamer-sys/dox", "glib/dox", "ser_de"]
ser_de = ["num-rational/serde", "serde", "serde_bytes", "serde_derive"]

[package.metadata.docs.rs]
features = ["dox", "embed-lgpl-docs"]
