[package]
name = "gstreamer"
version = "0.11.2"
authors = ["Sebastian Dr√∂ge <sebastian@centricular.com>"]
categories = ["api-bindings", "multimedia"]
description = "Rust bindings for GStreamer"
repository = "https://github.com/sdroege/gstreamer-rs"
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://gstreamer.freedesktop.org"
documentation = "https://sdroege.github.io/rustdoc/gstreamer/gstreamer"
keywords = ["gstreamer", "multimedia", "audio", "video", "gnome"]
build = "build.rs"

[dependencies]
bitflags = "1.0"
cfg-if = "0.1"
libc = "0.2"
glib-sys = "0.6"
gobject-sys = "0.6"
gstreamer-sys = { version = "0.5", features = ["v1_8"] }
glib = "0.5"
num-rational = { version = "0.1.38", default-features = false, features = [] }
lazy_static = "1.0"
futures = { version = "0.1", optional = true }
muldiv = "0.1.1"

[build-dependencies.rustdoc-stripper]
version = "0.1"
optional = true

[features]
v1_10 = ["gstreamer-sys/v1_10"]
v1_12 = ["gstreamer-sys/v1_12", "v1_10"]
v1_14 = ["gstreamer-sys/v1_14", "v1_12"]
embed-lgpl-docs = ["rustdoc-stripper"]
purge-lgpl-docs = ["rustdoc-stripper"]
dox = ["gstreamer-sys/dox", "glib/dox", "futures"]
default-features = []

[badges]
travis-ci = { repository = "sdroege/gstreamer-rs", branch = "master" }
