[options]
girs_dir = "../../gir-files"
library = "GstPlayer"
version = "1.0"
min_cfg_version = "1.12"
target_path = "."
work_mode = "sys"

extra_versions = [
    "1.18",
    "1.16",
    "1.14",
]

external_libraries = [
    "GLib",
    "GObject",
]

[external_libraries]
gstreamer="Gst"
gstreamer_video="GstVideo"
