[package]
name = "gstreamer-vulkan-xcb"
authors = ["Matthew Waters <matthew@centricular.com>"]
description = "Rust bindings for GStreamer Vulkan library (XCB support)"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://gstreamer.pages.freedesktop.org/gstreamer-rs/stable/latest/docs/gstreamer_vulkan_xcb/"
keywords = ["gstreamer", "multimedia", "audio", "video", "gnome"]
version.workspace = true
categories.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
libc = "0.2"
gstreamer-vulkan-xcb-sys.workspace = true
glib.workspace = true
gst.workspace = true
gst-vulkan.workspace = true

[dev-dependencies]
gir-format-check = "0.1"

[features]
default = []
v1_20 = ["gst/v1_20", "gst-vulkan/v1_20", "gstreamer-vulkan-xcb-sys/v1_20"]
v1_22 = ["gst/v1_22", "gst-vulkan/v1_22", "gstreamer-vulkan-xcb-sys/v1_22", "v1_20"]
v1_24 = ["gst/v1_24", "gst-vulkan/v1_24", "gstreamer-vulkan-xcb-sys/v1_24", "v1_22"]
v1_26 = ["gst/v1_26", "gst-vulkan/v1_26", "gstreamer-vulkan-xcb-sys/v1_26", "v1_24"]
v1_28 = ["gst/v1_28", "gst-vulkan/v1_28", "gstreamer-vulkan-xcb-sys/v1_28", "v1_26"]
v1_30 = ["gst/v1_30", "gst-vulkan/v1_30", "gstreamer-vulkan-xcb-sys/v1_30", "v1_28"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--generate-link-to-definition"]
