[options]
girs_directories = ["../../gir-files", "../../gst-gir-files"]
library = "Gst"
version = "1.0"
min_cfg_version = "1.14"
work_mode = "sys"
single_version_file = true

extra_versions = [
    "1.20",
    "1.18.3",
    "1.18",
    "1.16",
]

external_libraries = [
    "GLib",
    "GObject",
]

ignore = [
    "Gst.VERSION_MAJOR",
    "Gst.VERSION_MINOR",
    "Gst.VERSION_MICRO",
    "Gst.VERSION_NANO",
    "Gst.ERROR_SYSTEM",
    "Gst.TIME_FORMAT",
    "Gst.STIME_FORMAT",
    "Gst.TIMEP_FORMAT",
    "Gst.STIMEP_FORMAT",
    "Gst.PTR_FORMAT",
    "Gst.SEGMENT_FORMAT",
    "Gst.FOURCC_FORMAT",
]

[[object]]
name = "Gst.Buffer"
status = "generate"
    [[object.function]]
    name = "ref"
    version = "1.18.3"
    [[object.function]]
    name = "unref"
    version = "1.18.3"
    [[object.function]]
    name = "replace"
    version = "1.18.3"
    [[object.function]]
    name = "copy"
    version = "1.18.3"

[[object]]
name = "Gst.BufferList"
status = "generate"
    [[object.function]]
    name = "ref"
    version = "1.18.3"
    [[object.function]]
    name = "unref"
    version = "1.18.3"
    [[object.function]]
    name = "replace"
    version = "1.18.3"
    [[object.function]]
    name = "copy"
    version = "1.18.3"
    [[object.function]]
    name = "take"
    version = "1.18.3"

[[object]]
name = "Gst.*"
status = "generate"
    [[object.function]]
    name = "clear_buffer"
    version = "1.18.3"
    [[object.function]]
    name = "clear_buffer_list"
    version = "1.18.3"
    [[object.function]]
    name = "clear_caps"
    version = "1.18.3"
    [[object.function]]
    name = "clear_event"
    version = "1.18.3"
    [[object.function]]
    name = "clear_message"
    version = "1.18.3"
    [[object.function]]
    name = "clear_query"
    version = "1.18.3"
    [[object.function]]
    name = "clear_tag_list"
    version = "1.18.3"
    [[object.function]]
    name = "clear_uri"
    version = "1.18.3"

[[object]]
name = "Gst.Caps"
status = "generate"
    [[object.function]]
    name = "copy"
    version = "1.16"
    [[object.function]]
    name = "ref"
    version = "1.18.3"
    [[object.function]]
    name = "unref"
    version = "1.18.3"
    [[object.function]]
    name = "replace"
    version = "1.18.3"
    [[object.function]]
    name = "take"
    version = "1.18.3"

[[object]]
name = "Gst.Context"
status = "generate"
    [[object.function]]
    name = "ref"
    version = "1.18.3"
    [[object.function]]
    name = "unref"
    version = "1.18.3"
    [[object.function]]
    name = "copy"
    version = "1.18.3"
    [[object.function]]
    name = "replace"
    version = "1.18.3"

[[object]]
name = "Gst.Event"
status = "generate"
    [[object.function]]
    name = "copy"
    version = "1.18.3"
    [[object.function]]
    name = "ref"
    version = "1.18.3"
    [[object.function]]
    name = "unref"
    version = "1.18.3"
    [[object.function]]
    name = "replace"
    version = "1.18.3"
    [[object.function]]
    name = "take"
    version = "1.18.3"
    [[object.function]]
    name = "steal"
    version = "1.18.3"

[[object]]
name = "Gst.MiniObject"
status = "generate"
    [[object.function]]
    name = "get_type"
    version = "1.20"

[[object]]
name = "Gst.Memory"
status = "generate"
    [[object.function]]
    name = "ref"
    version = "1.18.3"
    [[object.function]]
    name = "unref"
    version = "1.18.3"

[[object]]
name = "Gst.Message"
status = "generate"
    [[object.function]]
    name = "copy"
    version = "1.18.3"
    [[object.function]]
    name = "ref"
    version = "1.18.3"
    [[object.function]]
    name = "unref"
    version = "1.18.3"
    [[object.function]]
    name = "replace"
    version = "1.18.3"
    [[object.function]]
    name = "take"
    version = "1.18.3"

[[object]]
name = "Gst.Promise"
status = "generate"
    [[object.function]]
    name = "ref"
    version = "1.18.3"
    [[object.function]]
    name = "unref"
    version = "1.18.3"

[[object]]
name = "Gst.Query"
status = "generate"
    [[object.function]]
    name = "copy"
    version = "1.18.3"
    [[object.function]]
    name = "ref"
    version = "1.18.3"
    [[object.function]]
    name = "unref"
    version = "1.18.3"
    [[object.function]]
    name = "replace"
    version = "1.18.3"
    [[object.function]]
    name = "take"
    version = "1.18.3"

[[object]]
name = "Gst.Sample"
status = "generate"
    [[object.function]]
    name = "copy"
    version = "1.18.3"
    [[object.function]]
    name = "ref"
    version = "1.18.3"
    [[object.function]]
    name = "unref"
    version = "1.18.3"

[[object]]
name = "Gst.TagList"
status = "generate"
    [[object.function]]
    name = "copy"
    version = "1.18.3"
    [[object.function]]
    name = "ref"
    version = "1.18.3"
    [[object.function]]
    name = "unref"
    version = "1.18.3"
    [[object.function]]
    name = "replace"
    version = "1.18.3"
    [[object.function]]
    name = "take"
    version = "1.18.3"

[[object]]
name = "Gst.Uri"
status = "generate"
    [[object.function]]
    name = "ref"
    version = "1.18.3"
    [[object.function]]
    name = "unref"
    version = "1.18.3"
    [[object.function]]
    name = "copy"
    version = "1.18.3"
