[package]
name = "tutorials"
version.workspace = true
license = "MIT"
authors = ["Sebastian Dr√∂ge <sebastian@centricular.com>"]
edition.workspace = true
rust-version.workspace = true

[dependencies]
glib.workspace = true
gst.workspace = true
gst-audio.workspace = true
gst-video = { workspace = true, optional = true }
gst-app.workspace = true
gst-pbutils.workspace = true
byte-slice-cast = "1"
anyhow = "1"
termion = { version = "3", optional = true }
async-channel = "2.0.0"
futures = "0.3"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.25"
objc = "0.2.7"

[[bin]]
name = "basic-tutorial-13"
required-features = ["termion"]

[[bin]]
name = "playback-tutorial-1"
required-features = ["termion"]

[[bin]]
name = "playback-tutorial-2"
required-features = ["termion"]

[[bin]]
name = "playback-tutorial-5"
required-features = ["termion", "gst-video"]
