[package]
name = "tutorials"
version = "0.10.0"
authors = ["Sebastian Dr√∂ge <sebastian@centricular.com>"]

[dependencies]
glib = { git = "https://github.com/gtk-rs/glib" }
gdk = { git = "https://github.com/gtk-rs/gdk", optional = true }
gtk = { git = "https://github.com/gtk-rs/gtk", features = ["v3_10"], optional = true }
gstreamer = { path = "../gstreamer" }
gstreamer-audio = { path = "../gstreamer-audio" }
gstreamer-video = { path = "../gstreamer-video" }
gstreamer-app = { path = "../gstreamer-app" }
send-cell = "0.1"
byte-slice-cast = "0.1"

[badges]
travis-ci = { repository = "sdroege/gstreamer-rs", branch = "master" }

[features]
tutorial5 = ["gtk", "gdk"]
tutorial5-x11 = ["tutorial5"]
tutorial5-quartz = ["tutorial5"]
