[package]
name = "examples"
version = "0.1.0"
authors = ["Sebastian Dr√∂ge <sebastian@centricular.com>"]

[dependencies]
glib = { version = "0.1.3", git = "https://github.com/gtk-rs/glib" }
gstreamer = { path = "../gstreamer" }
gstreamer-app = { path = "../gstreamer-app" }
gstreamer-audio = { path = "../gstreamer-audio" }
gstreamer-video = { path = "../gstreamer-video" }
gstreamer-player = { path = "../gstreamer-player", optional = true }
gtk = { version = "0.1.3", git = "https://github.com/gtk-rs/gtk", features = ["v3_6"] }
gio = { version = "0.1.3", git = "https://github.com/gtk-rs/gio" }
futures = "0.1"
tokio-core = "0.1"
send-cell = "0.1"
byte-slice-cast = "0.1"

[features]
gst-player = ["gstreamer-player"]
default-features = []

[badges]
travis-ci = { repository = "sdroege/gstreamer-rs", branch = "master" }
