[package]
name = "examples"
version = "0.1.0"
authors = ["Sebastian Dr√∂ge <sebastian@centricular.com>"]

[dependencies]
glib = { version = "0.1.3", git = "https://github.com/gtk-rs/glib" }
gstreamer = { path = "../gstreamer" }

[[bin]]
name = "launch"

[[bin]]
name = "launch_glib_main"

[[bin]]
name = "decodebin"
