[package]
name = "examples"
version = "0.11.0"
authors = ["Sebastian Dr√∂ge <sebastian@centricular.com>"]

[dependencies]
glib = { git = "https://github.com/gtk-rs/glib" }
gstreamer = { path = "../gstreamer" }
gstreamer-app = { path = "../gstreamer-app" }
gstreamer-audio = { path = "../gstreamer-audio" }
gstreamer-video = { path = "../gstreamer-video" }
gstreamer-player = { path = "../gstreamer-player", optional = true }
gstreamer-rtsp-server = { path = "../gstreamer-rtsp-server", optional = true }
gtk = { git = "https://github.com/gtk-rs/gtk", features = ["v3_6"], optional = true }
gdk = { git = "https://github.com/gtk-rs/gdk", optional = true }
gio = { git = "https://github.com/gtk-rs/gio", optional = true }
futures = { version = "0.1", optional = true }
tokio-core = { version = "0.1", optional = true }
send-cell = "0.1"
byte-slice-cast = "0.1"
failure = "0.1"
failure_derive = "0.1"

[features]
gst-player = ["gstreamer-player"]
gtksink = ["gtk", "gio"]
gtkvideooverlay = ["gtk", "gdk", "gio"]
gtkvideooverlay-x11 = ["gtkvideooverlay"]
gtkvideooverlay-quartz = ["gtkvideooverlay"]
tokio = ["gstreamer/futures", "futures", "tokio-core"]
gst-rtsp-server = ["gstreamer-rtsp-server"]
default-features = []
v1_10 = ["gstreamer/v1_10"]

[badges]
travis-ci = { repository = "sdroege/gstreamer-rs", branch = "master" }

[[bin]]
name = "appsink"

[[bin]]
name = "appsrc"

[[bin]]
name = "decodebin"

[[bin]]
name = "events"

[[bin]]
name = "gtksink"
required-features = ["gtksink"]

[[bin]]
name = "gtkvideooverlay"
required-features = ["gtkvideooverlay"]

[[bin]]
name = "iterator"

[[bin]]
name = "launch_glib_main"

[[bin]]
name = "launch"

[[bin]]
name = "pad_probes"

[[bin]]
name = "playbin"

[[bin]]
name = "player"
required-features = ["gst-player"]

[[bin]]
name = "queries"

[[bin]]
name = "rtpfecclient"

[[bin]]
name = "rtpfecserver"

[[bin]]
name = "rtsp-server"
required-features = ["gst-rtsp-server"]

[[bin]]
name = "tagsetter"

[[bin]]
name = "toc"

[[bin]]
name = "tokio"
required-features = ["tokio"]
