[package]
name = "gstreamer-tracing"
authors = ["Simonas Kazlauskas <tracing-gstreamer@kazlauskas.me>"]
categories = ["multimedia", "development-tools::debugging", "development-tools::profiling"]
description = "Bridge between GStreamer and the tracing ecosystem"
license = "MIT OR Apache-2.0"
keywords = ["gstreamer", "multimedia", "tracing", "logging"]
readme = "README.md"
documentation = "https://gstreamer.freedesktop.org/documentation/rust/stable/latest/docs/gst_tracing/"
version.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
gst = { workspace = true }
tracing = "0.1"
tracing-core = "0.1"
thread_local = "1.1"

[dev-dependencies]
tracing-subscriber = "0.3"

[features]
default = []
v1_22 = []
v1_24 = ["v1_22"]
v1_26 = ["v1_24"]
v1_28 = ["v1_26"]
v1_30 = ["gst/v1_30", "v1_28"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--generate-link-to-definition"]
