[options]
girs_directories = ["../../gir-files", "../../gst-gir-files"]
library = "GstPbutils"
version = "1.0"
min_cfg_version = "1.14"
work_mode = "sys"
single_version_file = true

extra_versions = [
    "1.24",
    "1.22",
    "1.20",
    "1.18",
    "1.16",
]

ignore = [
    "GstPbutils.PLUGINS_BASE_VERSION_MAJOR",
    "GstPbutils.PLUGINS_BASE_VERSION_MINOR",
    "GstPbutils.PLUGINS_BASE_VERSION_MICRO",
    "GstPbutils.PLUGINS_BASE_VERSION_NANO"
]

external_libraries = [
    "GLib",
    "GObject",
]

[external_libraries]
gstreamer="Gst"
gstreamer_audio="GstAudio"
gstreamer_video="GstVideo"
