[options]
girs_directories = ["../../gir-files", "../../gst-gir-files"]
library = "GstMse"
version = "1.0"
min_cfg_version = "1.26"
work_mode = "sys"
single_version_file = true

extra_versions = [
    "1.30",
    "1.28",
]

external_libraries = [
    "GLib",
]

generate = [
]

manual = [
    "Gst.Element",
    "Gst.Pad",
]

[external_libraries]
gstreamer="Gst"
