[options]
library = "GstPlayer"
version = "1.0"
min_cfg_version = "1.12"
work_mode = "normal"
concurrency = "send+sync"
generate_safety_asserts = true
single_version_file = true
generate_display_trait = false

external_libraries = [
    "GLib",
    "GObject",
    "Gst",
]

generate = [
    "GstPlayer.PlayerColorBalanceType",
    "GstPlayer.PlayerError",
    "GstPlayer.PlayerSignalDispatcher",
    "GstPlayer.PlayerSnapshotFormat",
    "GstPlayer.PlayerState",
    "GstPlayer.PlayerVideoRenderer",
    "GstPlayer.PlayerVisualization",
]

manual = [
    "GLib.Error",
    "GLib.MainContext",
    "GObject.Object",
    "Gst.Object",
    "Gst.Element",
    "GstVideo.VideoMultiviewFlags",
    "GstVideo.VideoMultiviewFramePacking",
]

[[object]]
name = "Gst.Caps"
status = "manual"
ref_mode = "ref"

[[object]]
name = "Gst.TagList"
status = "manual"
ref_mode = "ref"

[[object]]
name = "Gst.Sample"
status = "manual"
ref_mode = "ref"


[[object]]
name = "Gst.Structure"
status = "manual"
ref_mode = "ref-mut"

[[object]]
name = "GstPlayer.Player"
status = "generate"
final_type = true

    [[object.function]]
    name = "visualizations_free"
    # correct mutability
    ignore = true

    [[object.function]]
    name = "set_config"
    # Custom type
    manual = true

    [[object.function]]
    name = "new"
    ignore = true

    [[object.function]]
    name = "get_config"
    # Custom type
    manual = true

    [[object.function]]
    pattern = "config_.*"
    # Custom type
    ignore = true

    [[object.function]]
    name = "get_pipeline"
        [object.function.return]
        nullable = false

    [[object.function]]
    name = "set_audio_track"
        [object.function.return]
        bool_return_is_error = "Failed to set audio track"

    [[object.function]]
    name = "set_subtitle_track"
        [object.function.return]
        bool_return_is_error = "Failed to set subtitle track"

    [[object.function]]
    name = "set_video_track"
        [object.function.return]
        bool_return_is_error = "Failed to set video track"

    [[object.function]]
    name = "set_visualization"
        [[object.function.parameter]]
        name = "name"
        nullable = true

        [object.function.return]
        bool_return_is_error = "Failed to set visualization"

    [[object.signal]]
    name = "buffering"
    concurrency = "send"

    [[object.signal]]
    name = "duration-changed"
    concurrency = "send"
    # Pass ClockTime instead of u64
    manual = true

    [[object.signal]]
    name = "end-of-stream"
    concurrency = "send"

    [[object.signal]]
    name = "error"
    concurrency = "send"

    [[object.signal]]
    name = "media-info-updated"
    concurrency = "send"

    [[object.signal]]
    name = "mute-changed"
    concurrency = "send"

    [[object.signal]]
    name = "position-updated"
    concurrency = "send"
    # Pass ClockTime instead of u64
    manual = true

    [[object.signal]]
    name = "seek-done"
    concurrency = "send"
    # Pass ClockTime instead of u64
    manual = true

    [[object.signal]]
    name = "state-changed"
    concurrency = "send"

    [[object.signal]]
    name = "uri-loaded"
    concurrency = "send"

    [[object.signal]]
    name = "video-dimensions-changed"
    concurrency = "send"

    [[object.signal]]
    name = "volume-changed"
    concurrency = "send"

    [[object.signal]]
    name = "warning"
    concurrency = "send"

    [[object.property]]
    name = "subtitle-video-offset"
    version = "1.16"

[[object]]
name = "GstPlayer.PlayerStreamInfo"
status = "generate"

    [[object.function]]
    name = "get_stream_type"
    [object.function.return]
    nullable = false

[[object]]
name = "GstPlayer.PlayerAudioInfo"
status = "generate"
final_type = true

[[object]]
name = "GstPlayer.PlayerVideoInfo"
status = "generate"
final_type = true

    [[object.function]]
    name = "get_framerate"
    # Fraction
    manual = true

    [[object.function]]
    name = "get_pixel_aspect_ratio"
    # Fraction
    manual = true

[[object]]
name = "GstPlayer.PlayerSubtitleInfo"
status = "generate"
final_type = true

[[object]]
name = "GstPlayer.PlayerMediaInfo"
status = "generate"
final_type = true

    [[object.function]]
    name = "get_uri"
        [object.function.return]
        nullable = false

[[object]]
name = "GstPlayer.PlayerVideoOverlayVideoRenderer"
status = "generate"
final_type = true

[[object]]
name = "GstPlayer.PlayerGMainContextSignalDispatcher"
status = "generate"
final_type = true

    [[object.function]]
    name = "new"
    # Wrong return value
    ignore = true

[[object]]
name = "Gst.ClockTime"
status = "manual"
conversion_type = "scalar"
