[options]
girs_directories = ["../../gir-files", "../../gst-gir-files"]
library = "GstRtspServer"
version = "1.0"
min_cfg_version = "1.8"
work_mode = "sys"

extra_versions = [
    "1.20",
    "1.18",
    "1.16",
    "1.14",
    "1.12",
    "1.10",
]

external_libraries = [
    "GLib",
    "GObject",
    "Gio"
]

[external_libraries]
gstreamer="Gst"
gstreamer_net="GstNet"
gstreamer_sdp="GstSdp"
gstreamer_rtsp="GstRtsp"
