[package]
authors = ["Philippe Normand <philn@igalia.com>"]
build = "build.rs"
description = "FFI bindings to libgstvalidate-1.0"
documentation = "https://gstreamer.freedesktop.org/documentation/rust/stable/latest/docs/gstreamer_validate_sys/"
keywords = ["ffi", "gstreamer", "gnome", "multimedia"]
license = "MIT"
name = "gstreamer-validate-sys"
readme = "README.md"

[package.version]
workspace = true

[package.categories]
workspace = true

[package.repository]
workspace = true

[package.homepage]
workspace = true

[package.edition]
workspace = true

[package.rust-version]
workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--generate-link-to-definition"]
features = []

[package.metadata.system-deps.gstreamer_validate_1_0]
name = "gstreamer-validate-1.0"
version = "1.22"

[package.metadata.system-deps.gstreamer_validate_1_0.v1_24]
version = "1.24"

[package.metadata.system-deps.gstreamer_validate_1_0.v1_26]
version = "1.26"

[package.metadata.system-deps.gstreamer_validate_1_0.v1_28]
version = "1.28"

[package.metadata.system-deps.gstreamer_validate_1_0.v1_30]
version = "1.29"

[lib]
name = "gstreamer_validate_sys"

[build-dependencies]
system-deps = "7"

[dependencies]
libc = "0.2"

[dependencies.glib-sys]
workspace = true

[dependencies.gobject-sys]
workspace = true

[dependencies.gio-sys]
workspace = true

[dependencies.gstreamer-sys]
workspace = true

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
v1_24 = []
v1_26 = ["v1_24"]
v1_28 = ["v1_26"]
v1_30 = ["v1_28"]
