[options]
girs_directories = ["../../gir-files", "../../gst-gir-files"]
library = "GstValidate"
version = "1.0"
min_cfg_version = "1.22"
work_mode = "sys"
single_version_file = true

extra_versions = ["1.24"]

external_libraries = [
    "GLib",
    "Gio",
    "GObject",
]

[external_libraries]
gstreamer="Gst"
