[options]
girs_directories = ["../gir-files", "../gst-gir-files"]
library = "GstAnalytics"
version = "1.0"
min_cfg_version = "1.24"
work_mode = "normal"
concurrency = "send+sync"
generate_safety_asserts = true
single_version_file = true
generate_display_trait = false
trust_return_value_nullability = true

external_libraries = [
    "GLib",
    "GObject",
    "Gst",
]

generate = [
    "GstAnalytics.ModelInfoTensorDirection",
    "GstAnalytics.RelTypes",
    "GstAnalytics.TensorDataType",
    "GstAnalytics.TensorDimOrder"
]

manual = [
    "GLib.Quark",
    "GObject.Object",
    "Gst.Element",
    "Gst.MiniObject",
    "Gst.Object",
    "GstAnalytics.Tensor"
]


[[object]]
name = "Gst.Buffer"
status = "manual"
ref_mode = "ref"

[[object]]
name = "GstAnalytics.ModelInfo"
status = "generate"
    [[object.function]]
    pattern = ".+"
        [[object.function.parameter]]
        name = "modelinfo"
        const = true

    [[object.function]]
    name = "find_tensor_name"
    manual = true

    [[object.function]]
    name = "get_input_scales_offsets"
    manual = true

    [[object.function]]
    name = "get_target_ranges"
    manual = true
